### ISSUE TITLE
Могли б вы поделиться ios приложением ?

### ISSUE THREAD

**Issue by jhonnybonny** [Postuf/BTS#2]
Здравствуйте , я видел у вас удобное приложение )
Оно на swift или вы используете веб технологии ?
Ибо я пишу сейчас аналогичный проект на calypso и было бы не плохо взять за основу ваше мобильное приложение )

**Comment by Ririconj** [comment]
Доброго дня, iOS приложение представляет из себя простой HTTP клиент к HTTP-серверу, вызывающего методы из https://github.com/Postuf/BTS/blob/main/bin/sdrconsole.py. Не выкладываем его по причине того, чтобы сохранить универсальность применения проекта.
