### ISSUE TITLE
can we use hackrf?

### ISSUE THREAD

**Issue by 0x7a657573** [Postuf/BTS#3]
can we use hackrf?

**Comment by AsenOsen** [comment]
Of cource not - it is half-duplex

**Comment by 0x7a657573** [comment]
but If we use one hackrf for TX and another one for RX,will the answer still be negative?

**Comment by AsenOsen** [comment]
whole stack is aimed and configured for LimeSDR (including tool scripts)
so using HackRF could be possible only by rewriting a lot of code, also HackRF is much much weaker then LimeSDR

**Comment by Serga74** [comment]
can we usebladeRF 2.0 micro?
